# Generated by Django 3.1 on 2021-02-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210226_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
