# Generated by Django 3.1 on 2021-02-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210226_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='nomauteur',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
