# Generated by Django 3.1 on 2021-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_testimonial_nomauteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='agence',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
