# Generated by Django 3.1 on 2021-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210228_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='titre1',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='titre2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
