# Generated by Django 3.1 on 2021-02-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210228_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogequipe',
            name='images',
            field=models.FileField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
