# Generated by Django 3.1 on 2021-02-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogequipe_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
    ]
