# Generated by Django 3.1 on 2021-02-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210228_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogEquipe',
            new_name='Artequipe',
        ),
    ]
