# Generated by Django 3.1 on 2021-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210228_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='imageblog',
            field=models.FileField(default=1, upload_to='images/equipe/blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='titre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aequipe',
        ),
    ]
