# Generated by Django 3.1 on 2021-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210228_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='imageblog',
            field=models.FileField(upload_to='images/equipe'),
        ),
    ]
