# Generated by Django 3.1 on 2021-03-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_contact_newletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newletter',
            name='images',
        ),
        migrations.RemoveField(
            model_name='newletter',
            name='titre',
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newletter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
